services:
  db:
    image: 730335429934.dkr.ecr.us-east-1.amazonaws.com/dbdevop:latest
    container_name: tienda_db
    # ... (todo lo demás lo dejas exactamente igual)

  backend:
    image: 730335429934.dkr.ecr.us-east-1.amazonaws.com/backenddevop:latest
    container_name: tienda_backend
    # ... (todo lo demás lo dejas exactamente igual)

  frontend:
    image: 730335429934.dkr.ecr.us-east-1.amazonaws.com/frontenddevop:latest
    container_name: tienda_frontend
    # ... (todo lo demás lo dejas exactamente igual)
